passion: Drop TARGET_USES_GRALLOC1 * Creates a build error by including libgralloc1 headers instead of libgralloc
hardware/qcom-caf/msm8916/display/libqdutils/qdMetaData.cpp:39:10: fatal error: 'gralloc_priv.h' file not found
         ^~~~~~~~~~~~~~~~

Change-Id: Iaaa0b1583e96fee7471292a591737119a8963394